import {Image} from 'react-native';

const sources = {
  add: require('./assets/icons/add.png'),
  alertCaution: require('./assets/icons/alertCaution.png'),
  alertImportant: require('./assets/icons/alertImportant.png'),
  alertNote: require('./assets/icons/alertNote.png'),
  alertTip: require('./assets/icons/alertTip.png'),
  alertWarning: require('./assets/icons/alertWarning.png'),
  arrowDown: require('./assets/icons/arrowDown.png'),
  arrowRight: require('./assets/icons/arrowRight.png'),
  arrowUp: require('./assets/icons/arrowUp.png'),
  fullscreen: require('./assets/icons/fullscreen.png'),
  fileAdd: require('./assets/icons/fileAdd.png'),
  book: require('./assets/icons/book.png'),
  bookFill: require('./assets/icons/bookFill.png'),
  box: require('./assets/icons/box.png'),
  brain: require('./assets/icons/brain.png'),
  brand: require('./assets/icons/brand.png'),
  chat: require('./assets/icons/chat.png'),
  chatNew: require('./assets/icons/chatNew.png'),
  check: require('./assets/icons/check.png'),
  circle: require('./assets/icons/circle.png'),
  circleFill: require('./assets/icons/circleFill.png'),
  close: require('./assets/icons/close.png'),
  coins: require('./assets/icons/coins.png'),
  copy: require('./assets/icons/copy.png'),
  compaction: require('./assets/icons/compaction.png'),
  compactionSpin: require('./assets/icons/compactionSpin.png'),
  diff: require('./assets/icons/diff.png'),
  discuss: require('./assets/icons/discuss.png'),
  externalLink: require('./assets/icons/externalLink.png'),
  feedback: require('./assets/icons/feedback.png'),
  file: require('./assets/icons/file.png'),
  fileDiff: require('./assets/icons/fileDiff.png'),
  fileFill: require('./assets/icons/fileFill.png'),
  fileText: require('./assets/icons/fileText.png'),
  folder: require('./assets/icons/folder.png'),
  folderFill: require('./assets/icons/folderFill.png'),
  folderOpen: require('./assets/icons/folderOpen.png'),
  folderTab: require('./assets/icons/folderTab.png'),
  gitBranch: require('./assets/icons/gitBranch.png'),
  globe: require('./assets/icons/globe.png'),
  home: require('./assets/icons/home.png'),
  homeFill: require('./assets/icons/homeFill.png'),
  key: require('./assets/icons/key.png'),
  layout: require('./assets/icons/layout.png'),
  layoutGrid: require('./assets/icons/layoutGrid.png'),
  sliders: require('./assets/icons/sliders.png'),
  list: require('./assets/icons/list.png'),
  more: require('./assets/icons/more.png'),
  network: require('./assets/icons/network.png'),
  palette: require('./assets/icons/palette.png'),
  pencil: require('./assets/icons/pencil.png'),
  refresh: require('./assets/icons/refresh.png'),
  loader: require('./assets/icons/loader.png'),
  lock: require('./assets/icons/lock.png'),
  login: require('./assets/icons/login.png'),
  logout: require('./assets/icons/logout.png'),
  robot: require('./assets/icons/robot.png'),
  bard: require('./assets/icons/bard.png'),
  play: require('./assets/icons/play.png'),
  tools: require('./assets/icons/tools.png'),
  scan: require('./assets/icons/scan.png'),
  search: require('./assets/icons/search.png'),
  send: require('./assets/icons/send.png'),
  settings: require('./assets/icons/settings.png'),
  shield: require('./assets/icons/shield.png'),
  sparkle: require('./assets/icons/sparkle.png'),
  stack: require('./assets/icons/stack.png'),
  stop: require('./assets/icons/stop.png'),
  terminal: require('./assets/icons/terminal.png'),
  textWrap: require('./assets/icons/textWrap.png'),
  trash: require('./assets/icons/trash.png'),
} as const;

export type IconName = keyof typeof sources;

export function Icon({name, size = 16, color}: {name: IconName; size?: number; color: string}) {
  return <Image source={sources[name]} resizeMode="contain" style={{width: size, height: size, tintColor: color}} />;
}
