#!/usr/bin/env bun
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadIconSet } from "./fileIcons";
import { writeOrCheck } from "./generatedFiles";

const ICONS_DIR = join(import.meta.dir, "..", "public", "file-icons");
const MAP_PATH = join(import.meta.dir, "..", "src", "components", "fileIcons.generated.ts");

const set = loadIconSet();
const check = process.argv.includes("--check");

const entries = (source: Record<string, string>): string =>
	Object.entries(source)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([key, icon]) => `\t${JSON.stringify(key)}: ${JSON.stringify(icon)},`)
		.join("\n");

const map = `// Generated by \`bun run icons:generate\` from material-icon-theme v${set.version} — do not edit.
// The SVGs themselves are build output under public/file-icons; only this mapping is committed.

export const FILE_ICON_VERSION = ${JSON.stringify(set.version)};

export const FILE_ICON_FALLBACK = ${JSON.stringify(set.fallback)};

/** Whole filenames, which win over an extension: \`vitest.config.ts\` is not a TypeScript file icon. */
export const FILE_ICONS_BY_NAME: Record<string, string> = {
${entries(set.names)}
};

/** Longest extension first at lookup time, so \`d.ts\` beats \`ts\`. */
export const FILE_ICONS_BY_EXTENSION: Record<string, string> = {
${entries(set.extensions)}
};
`;

writeOrCheck({
	label: "icons",
	version: set.version,
	check,
	outputs: [{ path: MAP_PATH, content: map }],
});

// The icons are assets, not source: they are rewritten from the package on every build rather than
// reviewed as 1200 committed files. See panels/SPEC.md.
if (!check) {
	rmSync(ICONS_DIR, { recursive: true, force: true });
	mkdirSync(ICONS_DIR, { recursive: true });
	for (const [name, svg] of set.svgs) writeFileSync(join(ICONS_DIR, `${name}.svg`), `${svg}\n`);
	console.log(`icons: wrote ${set.svgs.size} recoloured icons to public/file-icons`);
}
