import {
	RiBarChartBoxFill,
	RiBarChartBoxLine,
	RiBookmarkFill,
	RiBookmarkLine,
	RiBookOpenFill,
	RiBookOpenLine,
	RiBracesLine,
	RiBugFill,
	RiBugLine,
	RiChat3Fill,
	RiChat3Line,
	RiCloudFill,
	RiCloudLine,
	RiCodeLine,
	RiCompass3Fill,
	RiCompass3Line,
	RiCpuFill,
	RiCpuLine,
	RiDatabase2Fill,
	RiDatabase2Line,
	RiDiscordFill,
	RiDiscordLine,
	RiEyeFill,
	RiEyeLine,
	RiFilePdf2Fill,
	RiFilePdf2Line,
	RiFileTextFill,
	RiFileTextLine,
	RiFlaskFill,
	RiFlaskLine,
	RiFolderFill,
	RiFolderLine,
	RiGitBranchFill,
	RiGitBranchLine,
	RiKey2Fill,
	RiKey2Line,
	RiLayoutFill,
	RiLayoutLine,
	RiMagicFill,
	RiMagicLine,
	RiOpenaiFill,
	RiOpenaiLine,
	RiPaletteFill,
	RiPaletteLine,
	RiPencilRuler2Fill,
	RiPencilRuler2Line,
	RiPlugFill,
	RiPlugLine,
	RiPuzzle2Fill,
	RiPuzzle2Line,
	RiRobot2Fill,
	RiRobot2Line,
	RiSettings3Fill,
	RiSettings3Line,
	RiShieldFill,
	RiShieldLine,
	RiStackFill,
	RiStackLine,
	RiTerminalBoxFill,
	RiTerminalBoxLine,
	RiTimerFill,
	RiTimerLine,
} from "@remixicon/react";
import type { ComponentType } from "react";

type Icon = ComponentType<{ className?: string | undefined }>;

const ICONS: Record<string, { line: Icon; fill?: Icon }> = {
	"book-open": { line: RiBookOpenLine, fill: RiBookOpenFill },
	"bar-chart-box": { line: RiBarChartBoxLine, fill: RiBarChartBoxFill },
	"terminal-box": { line: RiTerminalBoxLine, fill: RiTerminalBoxFill },
	"puzzle-2": { line: RiPuzzle2Line, fill: RiPuzzle2Fill },
	"robot-2": { line: RiRobot2Line, fill: RiRobot2Fill },
	"git-branch": { line: RiGitBranchLine, fill: RiGitBranchFill },
	"file-pdf-2": { line: RiFilePdf2Line, fill: RiFilePdf2Fill },
	"settings-3": { line: RiSettings3Line, fill: RiSettings3Fill },
	braces: { line: RiBracesLine },
	flask: { line: RiFlaskLine, fill: RiFlaskFill },
	"compass-3": { line: RiCompass3Line, fill: RiCompass3Fill },
	"pencil-ruler-2": { line: RiPencilRuler2Line, fill: RiPencilRuler2Fill },
	stack: { line: RiStackLine, fill: RiStackFill },
	layout: { line: RiLayoutLine, fill: RiLayoutFill },
	"chat-3": { line: RiChat3Line, fill: RiChat3Fill },
	plug: { line: RiPlugLine, fill: RiPlugFill },
	bug: { line: RiBugLine, fill: RiBugFill },
	magic: { line: RiMagicLine, fill: RiMagicFill },
	"database-2": { line: RiDatabase2Line, fill: RiDatabase2Fill },
	discord: { line: RiDiscordLine, fill: RiDiscordFill },
	"key-2": { line: RiKey2Line, fill: RiKey2Fill },
	shield: { line: RiShieldLine, fill: RiShieldFill },
	eye: { line: RiEyeLine, fill: RiEyeFill },
	timer: { line: RiTimerLine, fill: RiTimerFill },
	bookmark: { line: RiBookmarkLine, fill: RiBookmarkFill },
	folder: { line: RiFolderLine, fill: RiFolderFill },
	"file-text": { line: RiFileTextLine, fill: RiFileTextFill },
	code: { line: RiCodeLine },
	openai: { line: RiOpenaiLine, fill: RiOpenaiFill },
	cpu: { line: RiCpuLine, fill: RiCpuFill },
	cloud: { line: RiCloudLine, fill: RiCloudFill },
	palette: { line: RiPaletteLine, fill: RiPaletteFill },
};

const FALLBACK = RiPuzzle2Line;

export function pluginIcon(name: string, active = false): Icon {
	const entry = ICONS[name];
	if (!entry) return FALLBACK;
	return (active && entry.fill) || entry.line;
}
