#!/usr/bin/env bun
/**
 * Regenerate the list of settings keys Claude Code documents.
 *
 * Run by hand, and read the diff before committing: the build never fetches. A network call at build time
 * would make two builds of one commit differ, break offline CI, and let a docs redesign change what ships
 * without anyone seeing it. Drift here is a deliberate act instead.
 *
 * Only key *names* are taken. The descriptions are Anthropic's prose and stay where they are maintained;
 * the pane links to them. See claudeConfig/SPEC.md.
 *
 *   bun scripts/generate-claude-settings-keys.ts [--check]
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE = "https://code.claude.com/docs/en/settings-reference";
const TARGET = join(import.meta.dir, "..", "src", "claudeConfig", "settingsDocs.ts");

const HEADER = `// The settings keys Claude Code documents, and nothing else: the pane links each one to its entry in the
// reference rather than repeating Anthropic's prose, which is theirs and would ship inside an
// Apache-2.0 repository under a licence we cannot grant. A key name is the fact; the explanation stays
// where it is maintained.
//
// Generated by \`bun scripts/generate-claude-settings-keys.ts\`, which is run by hand and its diff read —
// see claudeConfig/SPEC.md. An unrecognized key means "newer than this list", never "invalid".`;

function render(keys: string[]): string {
	const list = keys.map((key) => `\t"${key}",`).join("\n");
	return `${HEADER}

export const CLAUDE_SETTINGS_DOC_KEYS: readonly string[] = [
${list}
];

const DOCS_URL = "${SOURCE}";

const DOCUMENTED = new Set(CLAUDE_SETTINGS_DOC_KEYS);

/**
 * The reference entry for a key, or its nearest documented ancestor — a nested key is explained by the
 * section above it. The anchor is the key lowercased with dots removed, which is the form the reference
 * uses; a fragment that ever stops matching lands the reader at the top of the right page rather than
 * anywhere wrong.
 */
export function settingsDocsUrl(key: string): string | undefined {
	let candidate = key;
	while (true) {
		if (DOCUMENTED.has(candidate)) {
			return \`\${DOCS_URL}#\${candidate.toLowerCase().replaceAll(".", "")}\`;
		}
		const cut = candidate.lastIndexOf(".");
		if (cut === -1) return undefined;
		candidate = candidate.slice(0, cut);
	}
}
`;
}

/** Each key is its own heading in the reference: ``### `someKey` `` — the same text its anchor is cut from. */
function extractKeys(markdown: string): string[] {
	const keys = new Set<string>();
	for (const match of markdown.matchAll(/^#{2,4}\s+`([A-Za-z][A-Za-z0-9._]*)`\s*$/gm)) {
		const key = match[1];
		if (key) keys.add(key);
	}
	return [...keys].sort();
}

const response = await fetch(SOURCE, { headers: { accept: "text/markdown, text/html" } });
if (!response.ok) {
	console.error(`could not read ${SOURCE}: ${response.status}`);
	process.exit(1);
}

const keys = extractKeys(await response.text());
if (keys.length < 20) {
	// The reference has dozens of keys; a handful means the page changed shape and the parse is wrong.
	// Writing that out would silently shrink the list, so refuse instead.
	console.error(`only ${keys.length} keys parsed — the reference's shape changed; fix the parser`);
	process.exit(1);
}

const rendered = render(keys);
if (process.argv.includes("--check")) {
	const current = await Bun.file(TARGET).text();
	if (current === rendered) {
		console.log(`claude settings keys: up to date (${keys.length})`);
		process.exit(0);
	}
	console.error("claude settings keys: out of date — run without --check and review the diff");
	process.exit(1);
}

writeFileSync(TARGET, rendered, "utf8");
console.log(`claude settings keys: wrote ${keys.length} keys to ${TARGET}`);
