#!/usr/bin/env bun
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE = "https://learn.chatgpt.com/docs/config-file/config-reference";
const TARGET = join(import.meta.dir, "..", "configKeys.ts");

const HEADER = `// The config.toml keys Codex documents and the type its reference gives each, nothing else — the
// descriptions are OpenAI's prose and stay where they are maintained; the pane links to them.
// Generated by \`bun scripts/generate-config-keys.ts\`, run by hand and its diff read — see SPEC.md.`;

function decode(text: string): string {
	return text
		.replaceAll("&quot;", '"')
		.replaceAll("&lt;", "<")
		.replaceAll("&gt;", ">")
		.replaceAll("&#39;", "'")
		.replaceAll("&amp;", "&");
}

function extract(html: string): [string, string][] {
	const rows: [string, string][] = [];
	const seen = new Set<string>();
	const pattern =
		/&quot;key&quot;:\[0,&quot;(.*?)&quot;\],&quot;type&quot;:\[0,&quot;(.*?)&quot;\]/g;
	for (const match of html.matchAll(pattern)) {
		const key = decode(match[1] ?? "");
		if (seen.has(key)) break;
		seen.add(key);
		rows.push([key, decode(match[2] ?? "")]);
	}
	return rows;
}

const response = await fetch(SOURCE);
if (!response.ok) {
	console.error(`could not read ${SOURCE}: ${response.status}`);
	process.exit(1);
}
const rows = extract(await response.text());
if (rows.length < 50) {
	console.error(`only ${rows.length} keys parsed — the reference's shape changed; fix the parser`);
	process.exit(1);
}
const body = rows
	.map(([key, type]) => `\t${JSON.stringify(key)}: ${JSON.stringify(type)},`)
	.join("\n");
const rendered = `${HEADER}\n\nexport const CODEX_CONFIG_DOCS_URL = "${SOURCE}";\n\nexport const CODEX_CONFIG_KEYS: Readonly<Record<string, string>> = {\n${body}\n};\n`;
if (process.argv.includes("--check")) {
	const current = await Bun.file(TARGET)
		.text()
		.catch(() => "");
	if (current !== rendered) {
		console.error("configKeys.ts is out of date with the reference");
		process.exit(1);
	}
} else {
	writeFileSync(TARGET, rendered);
	console.log(`${rows.length} keys → ${TARGET}`);
}
